apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: example
    image: gcr.io/google-samples/node-hello:1.0
    resources:
      limits:
        cpu: 0.5
        memory: 100Mi
  automountServiceAccountToken: false
